language: java
sudo: required
  
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    
before_script:
  - mvn install

script:
  - javac $(find . -name "*.java")

branches:
  only: master
