language: java
sudo: required

before_script:
  - mvn dependency:sources
  - mvn dependency:resolve -Dclassifier=javadoc
  - mvn dependency:resolve -Dclassifier=sources
  
script:
  - javac $(find . -name "*.java")

branches:
  only: master
  
addons:
  apt:
    packages:
      - oracle-java8-installer
