language: java
sudo: required
  
notifications:
    webhooks: https://www.travisbuddy.com/?insertMode=update
    
before_script:
  - mvn dependency:sources
  - mvn dependency:resolve -Dclassifier=javadoc
  
script:
  - javac $(find . -name "*.java")

branches:
  only: master
